export default {
  '0e384e19': [() => import(/* webpackChunkName: '0e384e19' */ "@site/docs/intro.md"), "@site/docs/intro.md", require.resolveWeak("@site/docs/intro.md")],
  '17896441': [() => import(/* webpackChunkName: '17896441' */ "@theme/DocItem"), "@theme/DocItem", require.resolveWeak("@theme/DocItem")],
  '17f354fe': [() => import(/* webpackChunkName: '17f354fe' */ "@site/docs/Pm assist/screenshot.md"), "@site/docs/Pm assist/screenshot.md", require.resolveWeak("@site/docs/Pm assist/screenshot.md")],
  '1be78505': [() => import(/* webpackChunkName: '1be78505' */ "@theme/DocPage"), "@theme/DocPage", require.resolveWeak("@theme/DocPage")],
  '1f391b9e': [() => import(/* webpackChunkName: '1f391b9e' */ "@theme/MDXPage"), "@theme/MDXPage", require.resolveWeak("@theme/MDXPage")],
  '2460277c': [() => import(/* webpackChunkName: '2460277c' */ "@site/docs/Pm assist/record.md"), "@site/docs/Pm assist/record.md", require.resolveWeak("@site/docs/Pm assist/record.md")],
  '393be207': [() => import(/* webpackChunkName: '393be207' */ "@site/src/pages/markdown-page.md"), "@site/src/pages/markdown-page.md", require.resolveWeak("@site/src/pages/markdown-page.md")],
  '3fb4f8c6': [() => import(/* webpackChunkName: '3fb4f8c6' */ "@site/docs/Pm_assist/screenshot.md"), "@site/docs/Pm_assist/screenshot.md", require.resolveWeak("@site/docs/Pm_assist/screenshot.md")],
  '5e9f5e1a': [() => import(/* webpackChunkName: '5e9f5e1a' */ "@generated/docusaurus.config"), "@generated/docusaurus.config", require.resolveWeak("@generated/docusaurus.config")],
  '6a732530': [() => import(/* webpackChunkName: '6a732530' */ "@site/docs/Pm_assist/miniext.md"), "@site/docs/Pm_assist/miniext.md", require.resolveWeak("@site/docs/Pm_assist/miniext.md")],
  '764daad6': [() => import(/* webpackChunkName: '764daad6' */ "@site/docs/Pm assist/miniext.md"), "@site/docs/Pm assist/miniext.md", require.resolveWeak("@site/docs/Pm assist/miniext.md")],
  '935f2afb': [() => import(/* webpackChunkName: '935f2afb' */ "~docs/default/version-current-metadata-prop-751.json"), "~docs/default/version-current-metadata-prop-751.json", require.resolveWeak("~docs/default/version-current-metadata-prop-751.json")],
  '9e4087bc': [() => import(/* webpackChunkName: '9e4087bc' */ "@theme/BlogArchivePage"), "@theme/BlogArchivePage", require.resolveWeak("@theme/BlogArchivePage")],
  'c4f5d8e4': [() => import(/* webpackChunkName: 'c4f5d8e4' */ "@site/src/pages/index.js"), "@site/src/pages/index.js", require.resolveWeak("@site/src/pages/index.js")],
  'dd14ef00': [() => import(/* webpackChunkName: 'dd14ef00' */ "~blog/default/quikly-docs-blog-archive-ea7.json"), "~blog/default/quikly-docs-blog-archive-ea7.json", require.resolveWeak("~blog/default/quikly-docs-blog-archive-ea7.json")],
  'f2540b9b': [() => import(/* webpackChunkName: 'f2540b9b' */ "@site/docs/Pm assist/starting_miniext.md"), "@site/docs/Pm assist/starting_miniext.md", require.resolveWeak("@site/docs/Pm assist/starting_miniext.md")],};
